---

- name: Setup Octo Raspberry Pi
  hosts: octopi

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml

  vars_prompt:
    - name: "APT_UPDATE"
      prompt: "Update Packages (default=no)?"
      private: false
    - name: "RPi_LCD_C"
      prompt: "3_2inch_RPi_LCD_C (default=no)?"
      private: false
    - name: "RPi_LCD_C"
      prompt: "3_5inch_RPi_LCD_C (default=no)?"
      private: false

  roles:
    - apt-update
    #- rpi_lcd
